export enum MIME_TYPE {
    Text = "text/plain",
    Json = "application/json",
    Html = "text/html",
    Form_Url_Encoded = "application/x-www-form-urlencoded",
    Css = "text/css",
    Csv = "text/csv",
    Js = "application/javascript",
    Bmp = "image/bmp",
    Jpeg = "image/jpeg",
    Gif = "image/gif",
    Ico = "image/x-icon",
    Png = "image/png",
    Pdf = "application/pdf",
    Svg = "image/svg+xml",
    Rtf = "application/rtf",
    Xml = "application/xml",
    Xls = "application/vnd.ms-excel",
    Xlsx = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    Ttf = "font/ttf",
    Woff = "font/woff",
    Woff2 = "font/woff2",
    Eot = "application/vnd.ms-fontobject",
    Otf = "font/otf",
    Swf = "application/x-shockwave-flash",
    Avi = "video/avi",

}